version: "3.9"
name: acme-platform
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command: ["redpanda","start","--overprovisioned","--smp=1","--memory=1G","--reserve-memory=0M","--check=false","--node-id=0","--kafka-addr=PLAINTEXT://0.0.0.0:9092","--advertise-kafka-addr=PLAINTEXT://redpanda:9092"]
    ports: ["9092:9092","9644:9644"]
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:9644/v1/status/ready"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: ["start-dev","--http-port=8080"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ["8080:8080"]
    depends_on: [postgres]
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 30

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:9090/-/ready"]
      interval: 5s
      timeout: 3s
      retries: 10

  grafana:
    image: grafana/grafana:11.1.4
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on: [prometheus]
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
